set nocp    "no compatible with vi
set nu      "line number
set rnu     "relative number 

set ts=4    "how \t show 
set et      "do not convert `ts` spaces to a \t, and convert a \t to `ts` spaces when indent changed
set sts=4   "how much columns of spaces a tab/backspace hitting pushes 

set ai      "auto indent 
set cindent "alternative indent option for C-like program 
set sw=4    "shift width when indenting

packadd! dracula
syntax enable
colorscheme dracula

set visualbell "turn off audio bell
set t_vb=      "turn off audio bell
